"""
blog_agent/config.py — Global constants and shared LLM instance.

All magic numbers live here. Change them in one place to tune the pipeline.
"""
from __future__ import annotations

from dotenv import load_dotenv
from langchain_mistralai import ChatMistralAI

load_dotenv()

# ── Model names ───────────────────────────────────────────────────────────────
MISTRAL_MODEL       = "mistral-medium-latest"
GEMINI_IMAGE_MODEL  = "gemini-2.5-flash-image"

# ── Recency windows (days) ────────────────────────────────────────────────────
OPEN_BOOK_RECENCY_DAYS   = 7      # Only last 7 days for breaking news
HYBRID_RECENCY_DAYS      = 45     # Last 45 days for evergreen + recent context
CLOSED_BOOK_RECENCY_DAYS = 3650   # ~10 years — effectively no cutoff

# ── Pipeline limits ───────────────────────────────────────────────────────────
MAX_QUERIES              = 10     # Max search queries generated by the router
MAX_TAVILY_RESULTS       = 6      # Tavily results fetched per query
MAX_EVIDENCE_FOR_PLAN    = 16     # Evidence items passed to the orchestrator
MAX_EVIDENCE_FOR_WORKER  = 20     # Evidence items passed to each worker
MAX_PAST_BLOGS_IN_UI     = 50     # Past blogs shown in the Streamlit sidebar

# ── Image generation ──────────────────────────────────────────────────────────
MAX_IMAGE_RETRIES        = 2      # Retry attempts before giving up on an image

# ── Shared LLM instance ───────────────────────────────────────────────────────
llm = ChatMistralAI(model=MISTRAL_MODEL)
